<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
echo '<meta http-equiv="X-UA-Compatible" content="ie=edge" />';
echo '<title>Simple House Template</title>';
echo '<link href="https://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" />';
echo '<link href="css/templatemo-style.css" rel="stylesheet" />';
echo '</head>';
echo '<!--';
echo '';
echo 'Simple House';
echo '';
echo 'https://templatemo.com/tm-539-simple-house';
echo '';
echo '-->';
echo '<body>';
echo '';
echo '<div class="container">';
echo '<!-- Top box -->';
echo '<!-- Logo & Site Name -->';
echo '<div class="placeholder">';
echo '<div class="parallax-window" data-parallax="scroll" data-image-src="img/simple-house-01.jpg">';
echo '<div class="tm-header">';
echo '<div class="row tm-header-inner">';
echo '<div class="col-md-6 col-12">';
echo '<img src="img/simple-house-logo.png" alt="Logo" class="tm-site-logo" />';
echo '<div class="tm-site-text-box">';
echo '<h1 class="tm-site-title">Simple House</h1>';
echo '<h6 class="tm-site-description">new restaurant template</h6>';
echo '</div>';
echo '</div>';
echo '<nav class="col-md-6 col-12 tm-nav">';
echo '<ul class="tm-nav-ul">';
echo '<li class="tm-nav-li"><a href="index.html" class="tm-nav-link active">Home</a></li>';
echo '<li class="tm-nav-li"><a href="login.php" class="tm-nav-link">Login/Register</a></li>';
echo '<li class="tm-nav-li"><a href="about.html" class="tm-nav-link">About</a></li>';
echo '<li class="tm-nav-li"><a href="contact.html" class="tm-nav-link">Contact</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<main>';
echo '<header class="row tm-welcome-section">';
echo '<h2 class="col-12 text-center tm-section-title">Welcome to Simple House</h2>';
echo '<p class="col-12 text-center">Total 3 HTML pages are included in this template. Header image has a parallax effect. You can feel free to download, edit and use this TemplateMo layout for your commercial or non-commercial websites.</p>';
echo '</header>';
echo '';
echo '<div class="tm-paging-links">';
echo '<nav>';
echo '<ul>';
echo '<li class="tm-paging-item"><a href="#" class="tm-paging-link active">Pizza</a></li>';
echo '<li class="tm-paging-item"><a href="#" class="tm-paging-link">Salad</a></li>';
echo '<li class="tm-paging-item"><a href="#" class="tm-paging-link">Noodle</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '';
echo '<!-- Gallery -->';
echo '<div class="row tm-gallery">';
echo '<!-- gallery page 1 -->';
echo '<div id="tm-gallery-page-pizza" class="tm-gallery-page">';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/01.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Fusce dictum finibus</h4>';
echo '<p class="tm-gallery-description">Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan</p>';
echo '<p class="tm-gallery-price">$45 / $55</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/02.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Aliquam sagittis</h4>';
echo '<p class="tm-gallery-description">Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan</p>';
echo '<p class="tm-gallery-price">$65 / $70</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/03.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Sed varius turpis</h4>';
echo '<p class="tm-gallery-description">Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan</p>';
echo '<p class="tm-gallery-price">$30.50</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/04.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Aliquam sagittis</h4>';
echo '<p class="tm-gallery-description">Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan</p>';
echo '<p class="tm-gallery-price">$25.50</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/05.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Maecenas eget justo</h4>';
echo '<p class="tm-gallery-description">Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan</p>';
echo '<p class="tm-gallery-price">$80.25</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/06.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Quisque et felis eros</h4>';
echo '<p class="tm-gallery-description">Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan</p>';
echo '<p class="tm-gallery-price">$20 / $40 / $60</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/07.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Sed ultricies dui</h4>';
echo '<p class="tm-gallery-description">Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan</p>';
echo '<p class="tm-gallery-price">$94</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/08.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Donec porta consequat</h4>';
echo '<p class="tm-gallery-description">Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan</p>';
echo '<p class="tm-gallery-price">$15</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '</div> <!-- gallery page 1 -->';
echo '';
echo '<!-- gallery page 2 -->';
echo '<div id="tm-gallery-page-salad" class="tm-gallery-page hidden">';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/04.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Salad Menu One</h4>';
echo '<p class="tm-gallery-description">Proin eu velit egestas, viverra sapien eget, consequat nunc. Vestibulum tristique</p>';
echo '<p class="tm-gallery-price">$25</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/03.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Second Title Salad</h4>';
echo '<p class="tm-gallery-description">Proin eu velit egestas, viverra sapien eget, consequat nunc. Vestibulum tristique</p>';
echo '<p class="tm-gallery-price">$30</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/05.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Third Salad Item</h4>';
echo '<p class="tm-gallery-description">Proin eu velit egestas, viverra sapien eget, consequat nunc. Vestibulum tristique</p>';
echo '<p class="tm-gallery-price">$45</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/01.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Superior Salad</h4>';
echo '<p class="tm-gallery-description">Proin eu velit egestas, viverra sapien eget, consequat nunc. Vestibulum tristique</p>';
echo '<p class="tm-gallery-price">$50</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/08.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Sed ultricies dui</h4>';
echo '<p class="tm-gallery-description">Proin eu velit egestas, viverra sapien eget, consequat nunc. Vestibulum tristique</p>';
echo '<p class="tm-gallery-price">$55 / $60</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/07.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Maecenas eget justo</h4>';
echo '<p class="tm-gallery-description">Proin eu velit egestas, viverra sapien eget, consequat nunc. Vestibulum tristique</p>';
echo '<p class="tm-gallery-price">$75</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '</div> <!-- gallery page 2 -->';
echo '';
echo '<!-- gallery page 3 -->';
echo '<div id="tm-gallery-page-noodle" class="tm-gallery-page hidden">';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/08.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Noodle One</h4>';
echo '<p class="tm-gallery-description">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>';
echo '<p class="tm-gallery-price">$12.50</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/07.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Noodle Second</h4>';
echo '<p class="tm-gallery-description">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>';
echo '<p class="tm-gallery-price">$15.50</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/06.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Third Soft Noodle</h4>';
echo '<p class="tm-gallery-description">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>';
echo '<p class="tm-gallery-price">$20.50</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/05.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Aliquam sagittis</h4>';
echo '<p class="tm-gallery-description">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>';
echo '<p class="tm-gallery-price">$30.25</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/04.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Maecenas eget justo</h4>';
echo '<p class="tm-gallery-description">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>';
echo '<p class="tm-gallery-price">$35.50</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/gallery/03.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Quisque et felis eros</h4>';
echo '<p class="tm-gallery-description">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>';
echo '<p class="tm-gallery-price">$40.50</p>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '';
echo '</div> <!-- gallery page 3 -->';
echo '</div>';
echo '<div class="tm-section tm-container-inner">';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<figure class="tm-description-figure">';
echo '<img src="img/img-01.jpg" alt="Image" class="img-fluid" />';
echo '</figure>';
echo '</div>';
echo '<div class="col-md-6">';
echo '<div class="tm-description-box">';
echo '<h4 class="tm-gallery-title">Maecenas nulla neque</h4>';
echo '<p class="tm-mb-45">Redistributing this template as a downloadable ZIP file on any template collection site is strictly prohibited. You will need to <a rel="nofollow" href="https://templatemo.com/contact">talk to us</a> for additional permissions about our templates. Thank you.</p>';
echo '<a href="about.html" class="tm-btn tm-btn-default tm-right">Read More</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</main>';
echo '';
echo '<footer class="tm-footer text-center">';
echo '<p>Copyright &copy; 2020 Simple House';
echo '';
echo '| Design: <a rel="nofollow" href="https://templatemo.com">TemplateMo</a></p>';
echo '</footer>';
echo '</div>';
echo '<script src="js/jquery.min.js"></script>';
echo '<script src="js/parallax.min.js"></script>';
echo '</body>';
echo '</html>';
?>
