<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
echo '<meta http-equiv="X-UA-Compatible" content="ie=edge" />';
echo '<title>Simple House Template</title>';
echo '<link href="https://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" />';
echo '<link href="css/templatemo-style.css" rel="stylesheet" />';
echo '</head>';
echo '<!--';
echo '';
echo 'Simple House';
echo '';
echo 'https://templatemo.com/tm-539-simple-house';
echo '';
echo '-->';
echo '<body>';
echo '';
echo '<div class="container">';
echo '<!-- Top box -->';
echo '<!-- Logo & Site Name -->';
echo '<div class="placeholder">';
echo '<div class="parallax-window" data-parallax="scroll" data-image-src="img/simple-house-01.jpg">';
echo '<div class="tm-header">';
echo '<div class="row tm-header-inner">';
echo '<div class="col-md-6 col-12">';
echo '<img src="img/simple-house-logo.png" alt="Logo" class="tm-site-logo" />';
echo '<div class="tm-site-text-box">';
echo '<h1 class="tm-site-title">Simple House</h1>';
echo '<h6 class="tm-site-description">new restaurant template</h6>';
echo '</div>';
echo '</div>';
echo '<nav class="col-md-6 col-12 tm-nav">';
echo '<ul class="tm-nav-ul">';
echo '<li class="tm-nav-li"><a href="index.html" class="tm-nav-link active">Home</a></li>';
echo '<li class="tm-nav-li"><a href="login.php" class="tm-nav-link">Login/Register</a></li>';
echo '<li class="tm-nav-li"><a href="about.html" class="tm-nav-link">About</a></li>';
echo '<li class="tm-nav-li"><a href="contact.html" class="tm-nav-link">Contact</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<main>';
echo '<header class="row tm-welcome-section">';
echo '<h2 class="col-12 text-center tm-section-title">Recent Lost Items</h2>';
echo '<p class="col-12 text-center">Total 3 HTML pages are included in this template. Header image has a parallax effect. You can feel free to download, edit and use this TemplateMo layout for your commercial or non-commercial websites.</p>';
echo '</header>';
echo '';
echo '';
echo '<!-- Gallery -->';
echo '<div class="row tm-gallery">';
echo '<!-- gallery page 1 -->';
echo '<div id="tm-gallery-page-pizza" class="tm-gallery-page">';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12">';
echo '<figure>';
echo '<img src="img/eraser.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Eraser</h4>';
echo '<p class="tm-gallery-description">Brief description...</p>';
echo '<a href="item.php">See item</a>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12">';
echo '<figure>';
echo '<img src="img/pen.jpg" alt="Image" class="img-fluid" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Pen</h4>';
echo '<p class="tm-gallery-description">Brief description...</p>';
echo '<a href="item.php">See item</a>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">';
echo '<figure>';
echo '<img src="img/watch.jpg" alt="Image" class="img-fluid tm-gallery-img" />';
echo '<figcaption>';
echo '<h4 class="tm-gallery-title">Watch</h4>';
echo '<p class="tm-gallery-description">Brief description...</p>';
echo '<a href="item.php">See item</a>';
echo '</figcaption>';
echo '</figure>';
echo '</article>';
echo '</div> <!-- gallery page 1 -->';
echo '';
echo '</div>';
echo '</main>';
echo '';
echo '<footer class="tm-footer text-center">';
echo '<p>Copyright &copy; 2020 Simple House';
echo '';
echo '| Design: <a rel="nofollow" href="https://templatemo.com">TemplateMo</a></p>';
echo '</footer>';
echo '</div>';
echo '<script src="js/jquery.min.js"></script>';
echo '<script src="js/parallax.min.js"></script>';
echo '</body>';
echo '</html>';
?>
