<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
echo '<meta http-equiv="X-UA-Compatible" content="ie=edge" />';
echo '<title>GotIt - Register</title>';
echo '<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet" />';
echo '<link href="css/all.min.css" rel="stylesheet" />';
echo '<link href="css/templatemo-style.css" rel="stylesheet" />';
echo '<link href="css/custom.css" media="all" rel="stylesheet" />';
echo '</head>';
echo '<!--';
echo '';
echo 'Simple House';
echo '';
echo 'https://templatemo.com/tm-539-simple-house';
echo '';
echo '-->';
echo '<body>';
echo '';
echo '<div class="container">';
echo '<!-- Top box -->';
echo '<!-- Logo & Site Name -->';
echo '<div class="custom-placeholder">';
echo '<div class="parallax-window">';
echo '<div class="tm-header">';
echo '<div class="row tm-header-inner">';
echo '<div class="col-md-6 col-12">';
echo '<div class="tm-site-text-box">';
echo '<img class="tm-site-logo" width="150" src = "img/logo.png"/>';
echo '</div>';
echo '</div>';
echo '<nav class="col-md-6 col-12 tm-nav">';
echo '<ul class="tm-nav-ul">';
echo '<li class="tm-nav-li"><a href="index.php" class="custom-link active">Home</a></li>';
echo '<li class="tm-nav-li"><a href="login.php" class="custom-link">Login/Register</a></li>';
echo '<li class="tm-nav-li"><a href="lostitemform.php" class="custom-link">Lost Item Report</a></li>';
echo '<li class="tm-nav-li"><a href="founditemform.php" class="custom-link">Found Item Report</a></li>';
echo '<li class="tm-nav-li"><a href="#" class="custom-link">Dashboard</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<main>';
echo '<header class="row tm-welcome-section">';
echo '<h2 class="col-12 text-center tm-section-title">Register Account</h2>';
echo '</header>';
echo '';
echo '<div class="tm-container-login" style="width: 70%">';
echo '<form action="" method="POST" class="tm-login-form">';
echo '';
echo '<div class="form-group">';
echo '<input type="text" name="name" class="form-control" placeholder="Name" required="" />';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input type="email" name="email" class="form-control" placeholder="Email" required="" />';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input type="password" name="password" class="form-control" placeholder="Password" required="" />';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input type="text" name="number" class="form-control" placeholder="Contact Number" required="" />';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input type="text" name="text" class="form-control" placeholder="Address" required="" />';
echo '</div>';
echo '';
echo '<div class="form-group tm-d-flex">';
echo '<button type="submit" class="tm-btn tm-btn-success tm-btn-right">';
echo 'Submit';
echo '</button>';
echo '</div>';
echo '</form>';
echo '<p> Have an account? <a href="login.php">Login here instead!</a></p>';
echo '</div>';
echo '';
echo '</main>';
echo '';
echo '<footer class="tm-footer text-center">';
echo '<p>Copyright &copy; 2020 Simple House';
echo '';
echo '| Design: <a rel="nofollow" href="https://templatemo.com">TemplateMo</a></p>';
echo '</footer>';
echo '</div>';
echo '<script src="js/jquery.min.js"></script>';
echo '<script src="js/parallax.min.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>
